language: python
python:
  - "2.7"
# install prerequisites
before_install:
  - sudo dpkg --add-architecture i386
  - sudo apt-get update -qq
  - sudo apt-get install -y build-essential python-numpy python-scipy python-gdal python-argparse python-dateutil libgdal-dev libproj-dev libxslt-dev libreadline-dev cython python-pandas python-h5py
  - sudo apt-get install -y wine winetricks
# install
install:
  - python bootstrap.py
  - ./bin/buildout
# testing
script:
  - ./bin/rheas -h
