language: python
python:
  - "2.7"
addons:
  postgresql: "9.3"
services:
  - postgresql
# install prerequisites
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y build-essential python-numpy python-scipy python-gdal python-argparse python-dateutil libgdal-dev libproj-dev libxslt-dev libreadline-dev cython python-pandas python-h5py python-psycopg2 python-pip
  - sudo apt-get install -y postgresql-9.3-postgis-2.1
  - sudo pip install netCDF4
  - sudo apt-get install -y wine winetricks
  - psql -U postgres -c "create extension postgis"
  - psql -U postgres -c "create extension postgis_topology"
  - python bootstrap.py
  - ln -s /usr/bin/psql ./bin/psql
  - ln -s /usr/bin/raster2pgsql ./bin/raster2pgsql
  - ln -s /usr/bin/shp2pgsql ./bin/shp2pgsql
# install
install:
  - ./bin/buildout -c .travis-buildout.cfg
# testing
script:
  - ./bin/rheas -h

